feat: implement URL Previews using Weavy embeds
weavy-labs/weavy-react-nextjs pull request #1
Opened 2023-08-14 05:07 UTC by vickywane

This PR will ship code changes for this codebase to add an example to demonstrate how URL Previews are implemented in a Weavy application using Weavy Embeds.

2023-08-14 12:06 UTC, lajjne requested changes
Added some comments. We should also update /pages/examples/messageapi.tsx to use an access_token instead of api key.

2023-08-14 12:06 UTC, lajjne commented on src/pages/examples/urlpreviews.tsx
> +        const tokenResponse = await fetch(`/api/token?refresh=${true}`);
refresh=true?

2023-08-14 14:43 UTC, vickywane commented on prisma/dev.db
I didn't make a code change to it. I, however ran the Prisma migration command. 

The `prisma/dev.db` command should be added to the `.gitignore` file. Since this is a local DB, Prisma will regenerate a new one each time the migration is run in a new environment. 

We can update the README to have developers run the migration command each time it's used for the first time, to create the DB using the Prisma schema.

2023-08-14 14:49 UTC, vickywane reviewed
Thank you for the review here.  @lajjne 

I will push a commit that removes the `.idea` folder and persists the `access_token` till it expires.

2023-08-14 14:49 UTC, vickywane commented on src/pages/examples/urlpreviews.tsx
> +        const tokenResponse = await fetch(`/api/token?refresh=${true}`);
Thank you for pointing this out. 

I will make an adjustment to it.

2023-08-17 08:16 UTC, klasjersevi commented
I'll try to checkout this PR to test it locally. I guess we are copying this into the mono-repo instead of merging in this repo when everything is ready @lajjne? So that our build distribution flow won't be affected?

2023-08-17 08:51 UTC, lajjne commented
@klasjersevi we are going to discard this PR so no need for you to review after all. 

But moving forward we will probably add other example code to the ACME demo repos, and yes we will need to copy it over to our mono-repo.

2023-08-17 09:01 UTC, closed without merging